name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        node-version: [12.x]

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup CI
      run: |
        nodejs --version
        npm --version
        npm ci

    - name: Build
      run: npm run build --if-present

    - name: Test
      run: npm run check